# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from vendor\ariasystems\api.list_payment_processors_m_api import ListPaymentProcessorsMApi  # noqa: E501
from swagger_client.rest import ApiException


class TestListPaymentProcessorsMApi(unittest.TestCase):
    """ListPaymentProcessorsMApi unit test stubs"""

    def setUp(self):
        self.api = vendor\ariasystems\api.list_payment_processors_m_api.ListPaymentProcessorsMApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_payment_processors_m(self):
        """Test case for list_payment_processors_m

        list_payment_processors_m  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
