# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from vendor\ariasystems\api.get_payment_details_m_api import GetPaymentDetailsMApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGetPaymentDetailsMApi(unittest.TestCase):
    """GetPaymentDetailsMApi unit test stubs"""

    def setUp(self):
        self.api = vendor\ariasystems\api.get_payment_details_m_api.GetPaymentDetailsMApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_payment_details_m(self):
        """Test case for get_payment_details_m

        get_payment_details_m  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
