# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.vendor\ariasystems\model.master_plan_plan_inst_field import MasterPlanPlanInstField  # noqa: E501
from swagger_client.rest import ApiException


class TestMasterPlanPlanInstField(unittest.TestCase):
    """MasterPlanPlanInstField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMasterPlanPlanInstField(self):
        """Test MasterPlanPlanInstField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.master_plan_plan_inst_field.MasterPlanPlanInstField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
