# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.vendor\ariasystems\model.get_account_details_m_request import GetAccountDetailsMRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestGetAccountDetailsMRequest(unittest.TestCase):
    """GetAccountDetailsMRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAccountDetailsMRequest(self):
        """Test GetAccountDetailsMRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_account_details_m_request.GetAccountDetailsMRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
