# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.vendor\ariasystems\model.matching_contact import MatchingContact  # noqa: E501
from swagger_client.rest import ApiException


class TestMatchingContact(unittest.TestCase):
    """MatchingContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMatchingContact(self):
        """Test MatchingContact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.matching_contact.MatchingContact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
