# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.vendor\ariasystems\model.get_transaction_information_m_response import GetTransactionInformationMResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetTransactionInformationMResponse(unittest.TestCase):
    """GetTransactionInformationMResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTransactionInformationMResponse(self):
        """Test GetTransactionInformationMResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_transaction_information_m_response.GetTransactionInformationMResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
