# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.vendor\ariasystems\model.get_coupon_history_m_request import GetCouponHistoryMRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestGetCouponHistoryMRequest(unittest.TestCase):
    """GetCouponHistoryMRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCouponHistoryMRequest(self):
        """Test GetCouponHistoryMRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_coupon_history_m_request.GetCouponHistoryMRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
