# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.vendor\ariasystems\model.coupon_history_m import CouponHistoryM  # noqa: E501
from swagger_client.rest import ApiException


class TestCouponHistoryM(unittest.TestCase):
    """CouponHistoryM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCouponHistoryM(self):
        """Test CouponHistoryM"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.coupon_history_m.CouponHistoryM()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
