# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from vendor\ariasystems\api.get_transaction_information_m_api import GetTransactionInformationMApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGetTransactionInformationMApi(unittest.TestCase):
    """GetTransactionInformationMApi unit test stubs"""

    def setUp(self):
        self.api = vendor\ariasystems\api.get_transaction_information_m_api.GetTransactionInformationMApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_transaction_information_m(self):
        """Test case for get_transaction_information_m

        get_transaction_information_m  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
