# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from vendor\ariasystems\api.get_coupon_history_m_api import GetCouponHistoryMApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGetCouponHistoryMApi(unittest.TestCase):
    """GetCouponHistoryMApi unit test stubs"""

    def setUp(self):
        self.api = vendor\ariasystems\api.get_coupon_history_m_api.GetCouponHistoryMApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_coupon_history_m(self):
        """Test case for get_coupon_history_m

        get_coupon_history_m  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
