# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.vendor\ariasystems\model.supp_plan_plan_inst_field import SuppPlanPlanInstField  # noqa: E501
from swagger_client.rest import ApiException


class TestSuppPlanPlanInstField(unittest.TestCase):
    """SuppPlanPlanInstField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuppPlanPlanInstField(self):
        """Test SuppPlanPlanInstField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.supp_plan_plan_inst_field.SuppPlanPlanInstField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
