# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.vendor\ariasystems\model.list_payment_methods_m_response import ListPaymentMethodsMResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestListPaymentMethodsMResponse(unittest.TestCase):
    """ListPaymentMethodsMResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListPaymentMethodsMResponse(self):
        """Test ListPaymentMethodsMResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_payment_methods_m_response.ListPaymentMethodsMResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
