# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AccountPlanHistoryM(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'plan_instance_no': 'int',
        'client_plan_instance_id': 'int',
        'master_plan_instance_no': 'int',
        'mp_client_plan_instance_id': 'int',
        'old_plan_name': 'str',
        'old_plan_no': 'int',
        'old_client_plan_id': 'str',
        'old_client_plan_instance_id': 'int',
        'old_promo_cd': 'str',
        'old_status_cd': 'str',
        'old_plan_units': 'int',
        'old_rate_schedule_no': 'int',
        'old_client_rate_schedule_id': 'str',
        'new_plan_name': 'str',
        'new_plan_no': 'int',
        'new_client_plan_id': 'str',
        'new_client_plan_instance_id': 'int',
        'new_promo_cd': 'str',
        'new_status_cd': 'str',
        'new_plan_units': 'int',
        'new_rate_schedule_no': 'int',
        'new_client_rate_schedule_id': 'str',
        'old_dunning_state': 'int',
        'new_dunning_state': 'int'
    }

    attribute_map = {
        'plan_instance_no': 'plan_instance_no',
        'client_plan_instance_id': 'client_plan_instance_id',
        'master_plan_instance_no': 'master_plan_instance_no',
        'mp_client_plan_instance_id': 'mp_client_plan_instance_id',
        'old_plan_name': 'old_plan_name',
        'old_plan_no': 'old_plan_no',
        'old_client_plan_id': 'old_client_plan_id',
        'old_client_plan_instance_id': 'old_client_plan_instance_id',
        'old_promo_cd': 'old_promo_cd',
        'old_status_cd': 'old_status_cd',
        'old_plan_units': 'old_plan_units',
        'old_rate_schedule_no': 'old_rate_schedule_no',
        'old_client_rate_schedule_id': 'old_client_rate_schedule_id',
        'new_plan_name': 'new_plan_name',
        'new_plan_no': 'new_plan_no',
        'new_client_plan_id': 'new_client_plan_id',
        'new_client_plan_instance_id': 'new_client_plan_instance_id',
        'new_promo_cd': 'new_promo_cd',
        'new_status_cd': 'new_status_cd',
        'new_plan_units': 'new_plan_units',
        'new_rate_schedule_no': 'new_rate_schedule_no',
        'new_client_rate_schedule_id': 'new_client_rate_schedule_id',
        'old_dunning_state': 'old_dunning_state',
        'new_dunning_state': 'new_dunning_state'
    }

    def __init__(self, plan_instance_no=None, client_plan_instance_id=None, master_plan_instance_no=None, mp_client_plan_instance_id=None, old_plan_name=None, old_plan_no=None, old_client_plan_id=None, old_client_plan_instance_id=None, old_promo_cd=None, old_status_cd=None, old_plan_units=None, old_rate_schedule_no=None, old_client_rate_schedule_id=None, new_plan_name=None, new_plan_no=None, new_client_plan_id=None, new_client_plan_instance_id=None, new_promo_cd=None, new_status_cd=None, new_plan_units=None, new_rate_schedule_no=None, new_client_rate_schedule_id=None, old_dunning_state=None, new_dunning_state=None):  # noqa: E501
        """AccountPlanHistoryM - a model defined in Swagger"""  # noqa: E501

        self._plan_instance_no = None
        self._client_plan_instance_id = None
        self._master_plan_instance_no = None
        self._mp_client_plan_instance_id = None
        self._old_plan_name = None
        self._old_plan_no = None
        self._old_client_plan_id = None
        self._old_client_plan_instance_id = None
        self._old_promo_cd = None
        self._old_status_cd = None
        self._old_plan_units = None
        self._old_rate_schedule_no = None
        self._old_client_rate_schedule_id = None
        self._new_plan_name = None
        self._new_plan_no = None
        self._new_client_plan_id = None
        self._new_client_plan_instance_id = None
        self._new_promo_cd = None
        self._new_status_cd = None
        self._new_plan_units = None
        self._new_rate_schedule_no = None
        self._new_client_rate_schedule_id = None
        self._old_dunning_state = None
        self._new_dunning_state = None
        self.discriminator = None

        if plan_instance_no is not None:
            self.plan_instance_no = plan_instance_no
        if client_plan_instance_id is not None:
            self.client_plan_instance_id = client_plan_instance_id
        if master_plan_instance_no is not None:
            self.master_plan_instance_no = master_plan_instance_no
        if mp_client_plan_instance_id is not None:
            self.mp_client_plan_instance_id = mp_client_plan_instance_id
        if old_plan_name is not None:
            self.old_plan_name = old_plan_name
        if old_plan_no is not None:
            self.old_plan_no = old_plan_no
        if old_client_plan_id is not None:
            self.old_client_plan_id = old_client_plan_id
        if old_client_plan_instance_id is not None:
            self.old_client_plan_instance_id = old_client_plan_instance_id
        if old_promo_cd is not None:
            self.old_promo_cd = old_promo_cd
        if old_status_cd is not None:
            self.old_status_cd = old_status_cd
        if old_plan_units is not None:
            self.old_plan_units = old_plan_units
        if old_rate_schedule_no is not None:
            self.old_rate_schedule_no = old_rate_schedule_no
        if old_client_rate_schedule_id is not None:
            self.old_client_rate_schedule_id = old_client_rate_schedule_id
        if new_plan_name is not None:
            self.new_plan_name = new_plan_name
        if new_plan_no is not None:
            self.new_plan_no = new_plan_no
        if new_client_plan_id is not None:
            self.new_client_plan_id = new_client_plan_id
        if new_client_plan_instance_id is not None:
            self.new_client_plan_instance_id = new_client_plan_instance_id
        if new_promo_cd is not None:
            self.new_promo_cd = new_promo_cd
        if new_status_cd is not None:
            self.new_status_cd = new_status_cd
        if new_plan_units is not None:
            self.new_plan_units = new_plan_units
        if new_rate_schedule_no is not None:
            self.new_rate_schedule_no = new_rate_schedule_no
        if new_client_rate_schedule_id is not None:
            self.new_client_rate_schedule_id = new_client_rate_schedule_id
        if old_dunning_state is not None:
            self.old_dunning_state = old_dunning_state
        if new_dunning_state is not None:
            self.new_dunning_state = new_dunning_state

    @property
    def plan_instance_no(self):
        """Gets the plan_instance_no of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The plan_instance_no of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._plan_instance_no

    @plan_instance_no.setter
    def plan_instance_no(self, plan_instance_no):
        """Sets the plan_instance_no of this AccountPlanHistoryM.

          # noqa: E501

        :param plan_instance_no: The plan_instance_no of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._plan_instance_no = plan_instance_no

    @property
    def client_plan_instance_id(self):
        """Gets the client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._client_plan_instance_id

    @client_plan_instance_id.setter
    def client_plan_instance_id(self, client_plan_instance_id):
        """Sets the client_plan_instance_id of this AccountPlanHistoryM.

          # noqa: E501

        :param client_plan_instance_id: The client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._client_plan_instance_id = client_plan_instance_id

    @property
    def master_plan_instance_no(self):
        """Gets the master_plan_instance_no of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The master_plan_instance_no of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._master_plan_instance_no

    @master_plan_instance_no.setter
    def master_plan_instance_no(self, master_plan_instance_no):
        """Sets the master_plan_instance_no of this AccountPlanHistoryM.

          # noqa: E501

        :param master_plan_instance_no: The master_plan_instance_no of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._master_plan_instance_no = master_plan_instance_no

    @property
    def mp_client_plan_instance_id(self):
        """Gets the mp_client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The mp_client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._mp_client_plan_instance_id

    @mp_client_plan_instance_id.setter
    def mp_client_plan_instance_id(self, mp_client_plan_instance_id):
        """Sets the mp_client_plan_instance_id of this AccountPlanHistoryM.

          # noqa: E501

        :param mp_client_plan_instance_id: The mp_client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._mp_client_plan_instance_id = mp_client_plan_instance_id

    @property
    def old_plan_name(self):
        """Gets the old_plan_name of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The old_plan_name of this AccountPlanHistoryM.  # noqa: E501
        :rtype: str
        """
        return self._old_plan_name

    @old_plan_name.setter
    def old_plan_name(self, old_plan_name):
        """Sets the old_plan_name of this AccountPlanHistoryM.

          # noqa: E501

        :param old_plan_name: The old_plan_name of this AccountPlanHistoryM.  # noqa: E501
        :type: str
        """

        self._old_plan_name = old_plan_name

    @property
    def old_plan_no(self):
        """Gets the old_plan_no of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The old_plan_no of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._old_plan_no

    @old_plan_no.setter
    def old_plan_no(self, old_plan_no):
        """Sets the old_plan_no of this AccountPlanHistoryM.

          # noqa: E501

        :param old_plan_no: The old_plan_no of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._old_plan_no = old_plan_no

    @property
    def old_client_plan_id(self):
        """Gets the old_client_plan_id of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The old_client_plan_id of this AccountPlanHistoryM.  # noqa: E501
        :rtype: str
        """
        return self._old_client_plan_id

    @old_client_plan_id.setter
    def old_client_plan_id(self, old_client_plan_id):
        """Sets the old_client_plan_id of this AccountPlanHistoryM.

          # noqa: E501

        :param old_client_plan_id: The old_client_plan_id of this AccountPlanHistoryM.  # noqa: E501
        :type: str
        """

        self._old_client_plan_id = old_client_plan_id

    @property
    def old_client_plan_instance_id(self):
        """Gets the old_client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The old_client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._old_client_plan_instance_id

    @old_client_plan_instance_id.setter
    def old_client_plan_instance_id(self, old_client_plan_instance_id):
        """Sets the old_client_plan_instance_id of this AccountPlanHistoryM.

          # noqa: E501

        :param old_client_plan_instance_id: The old_client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._old_client_plan_instance_id = old_client_plan_instance_id

    @property
    def old_promo_cd(self):
        """Gets the old_promo_cd of this AccountPlanHistoryM.  # noqa: E501

        Promotion code used for the Plan  # noqa: E501

        :return: The old_promo_cd of this AccountPlanHistoryM.  # noqa: E501
        :rtype: str
        """
        return self._old_promo_cd

    @old_promo_cd.setter
    def old_promo_cd(self, old_promo_cd):
        """Sets the old_promo_cd of this AccountPlanHistoryM.

        Promotion code used for the Plan  # noqa: E501

        :param old_promo_cd: The old_promo_cd of this AccountPlanHistoryM.  # noqa: E501
        :type: str
        """

        self._old_promo_cd = old_promo_cd

    @property
    def old_status_cd(self):
        """Gets the old_status_cd of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The old_status_cd of this AccountPlanHistoryM.  # noqa: E501
        :rtype: str
        """
        return self._old_status_cd

    @old_status_cd.setter
    def old_status_cd(self, old_status_cd):
        """Sets the old_status_cd of this AccountPlanHistoryM.

          # noqa: E501

        :param old_status_cd: The old_status_cd of this AccountPlanHistoryM.  # noqa: E501
        :type: str
        """

        self._old_status_cd = old_status_cd

    @property
    def old_plan_units(self):
        """Gets the old_plan_units of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The old_plan_units of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._old_plan_units

    @old_plan_units.setter
    def old_plan_units(self, old_plan_units):
        """Sets the old_plan_units of this AccountPlanHistoryM.

          # noqa: E501

        :param old_plan_units: The old_plan_units of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._old_plan_units = old_plan_units

    @property
    def old_rate_schedule_no(self):
        """Gets the old_rate_schedule_no of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The old_rate_schedule_no of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._old_rate_schedule_no

    @old_rate_schedule_no.setter
    def old_rate_schedule_no(self, old_rate_schedule_no):
        """Sets the old_rate_schedule_no of this AccountPlanHistoryM.

          # noqa: E501

        :param old_rate_schedule_no: The old_rate_schedule_no of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._old_rate_schedule_no = old_rate_schedule_no

    @property
    def old_client_rate_schedule_id(self):
        """Gets the old_client_rate_schedule_id of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The old_client_rate_schedule_id of this AccountPlanHistoryM.  # noqa: E501
        :rtype: str
        """
        return self._old_client_rate_schedule_id

    @old_client_rate_schedule_id.setter
    def old_client_rate_schedule_id(self, old_client_rate_schedule_id):
        """Sets the old_client_rate_schedule_id of this AccountPlanHistoryM.

          # noqa: E501

        :param old_client_rate_schedule_id: The old_client_rate_schedule_id of this AccountPlanHistoryM.  # noqa: E501
        :type: str
        """

        self._old_client_rate_schedule_id = old_client_rate_schedule_id

    @property
    def new_plan_name(self):
        """Gets the new_plan_name of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The new_plan_name of this AccountPlanHistoryM.  # noqa: E501
        :rtype: str
        """
        return self._new_plan_name

    @new_plan_name.setter
    def new_plan_name(self, new_plan_name):
        """Sets the new_plan_name of this AccountPlanHistoryM.

          # noqa: E501

        :param new_plan_name: The new_plan_name of this AccountPlanHistoryM.  # noqa: E501
        :type: str
        """

        self._new_plan_name = new_plan_name

    @property
    def new_plan_no(self):
        """Gets the new_plan_no of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The new_plan_no of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._new_plan_no

    @new_plan_no.setter
    def new_plan_no(self, new_plan_no):
        """Sets the new_plan_no of this AccountPlanHistoryM.

          # noqa: E501

        :param new_plan_no: The new_plan_no of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._new_plan_no = new_plan_no

    @property
    def new_client_plan_id(self):
        """Gets the new_client_plan_id of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The new_client_plan_id of this AccountPlanHistoryM.  # noqa: E501
        :rtype: str
        """
        return self._new_client_plan_id

    @new_client_plan_id.setter
    def new_client_plan_id(self, new_client_plan_id):
        """Sets the new_client_plan_id of this AccountPlanHistoryM.

          # noqa: E501

        :param new_client_plan_id: The new_client_plan_id of this AccountPlanHistoryM.  # noqa: E501
        :type: str
        """

        self._new_client_plan_id = new_client_plan_id

    @property
    def new_client_plan_instance_id(self):
        """Gets the new_client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The new_client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._new_client_plan_instance_id

    @new_client_plan_instance_id.setter
    def new_client_plan_instance_id(self, new_client_plan_instance_id):
        """Sets the new_client_plan_instance_id of this AccountPlanHistoryM.

          # noqa: E501

        :param new_client_plan_instance_id: The new_client_plan_instance_id of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._new_client_plan_instance_id = new_client_plan_instance_id

    @property
    def new_promo_cd(self):
        """Gets the new_promo_cd of this AccountPlanHistoryM.  # noqa: E501

        Promotion code used for the Plan  # noqa: E501

        :return: The new_promo_cd of this AccountPlanHistoryM.  # noqa: E501
        :rtype: str
        """
        return self._new_promo_cd

    @new_promo_cd.setter
    def new_promo_cd(self, new_promo_cd):
        """Sets the new_promo_cd of this AccountPlanHistoryM.

        Promotion code used for the Plan  # noqa: E501

        :param new_promo_cd: The new_promo_cd of this AccountPlanHistoryM.  # noqa: E501
        :type: str
        """

        self._new_promo_cd = new_promo_cd

    @property
    def new_status_cd(self):
        """Gets the new_status_cd of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The new_status_cd of this AccountPlanHistoryM.  # noqa: E501
        :rtype: str
        """
        return self._new_status_cd

    @new_status_cd.setter
    def new_status_cd(self, new_status_cd):
        """Sets the new_status_cd of this AccountPlanHistoryM.

          # noqa: E501

        :param new_status_cd: The new_status_cd of this AccountPlanHistoryM.  # noqa: E501
        :type: str
        """

        self._new_status_cd = new_status_cd

    @property
    def new_plan_units(self):
        """Gets the new_plan_units of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The new_plan_units of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._new_plan_units

    @new_plan_units.setter
    def new_plan_units(self, new_plan_units):
        """Sets the new_plan_units of this AccountPlanHistoryM.

          # noqa: E501

        :param new_plan_units: The new_plan_units of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._new_plan_units = new_plan_units

    @property
    def new_rate_schedule_no(self):
        """Gets the new_rate_schedule_no of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The new_rate_schedule_no of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._new_rate_schedule_no

    @new_rate_schedule_no.setter
    def new_rate_schedule_no(self, new_rate_schedule_no):
        """Sets the new_rate_schedule_no of this AccountPlanHistoryM.

          # noqa: E501

        :param new_rate_schedule_no: The new_rate_schedule_no of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._new_rate_schedule_no = new_rate_schedule_no

    @property
    def new_client_rate_schedule_id(self):
        """Gets the new_client_rate_schedule_id of this AccountPlanHistoryM.  # noqa: E501

          # noqa: E501

        :return: The new_client_rate_schedule_id of this AccountPlanHistoryM.  # noqa: E501
        :rtype: str
        """
        return self._new_client_rate_schedule_id

    @new_client_rate_schedule_id.setter
    def new_client_rate_schedule_id(self, new_client_rate_schedule_id):
        """Sets the new_client_rate_schedule_id of this AccountPlanHistoryM.

          # noqa: E501

        :param new_client_rate_schedule_id: The new_client_rate_schedule_id of this AccountPlanHistoryM.  # noqa: E501
        :type: str
        """

        self._new_client_rate_schedule_id = new_client_rate_schedule_id

    @property
    def old_dunning_state(self):
        """Gets the old_dunning_state of this AccountPlanHistoryM.  # noqa: E501

        Previous dunning state of the plan instance.  # noqa: E501

        :return: The old_dunning_state of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._old_dunning_state

    @old_dunning_state.setter
    def old_dunning_state(self, old_dunning_state):
        """Sets the old_dunning_state of this AccountPlanHistoryM.

        Previous dunning state of the plan instance.  # noqa: E501

        :param old_dunning_state: The old_dunning_state of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._old_dunning_state = old_dunning_state

    @property
    def new_dunning_state(self):
        """Gets the new_dunning_state of this AccountPlanHistoryM.  # noqa: E501

        Current dunning state of the plan instance.  # noqa: E501

        :return: The new_dunning_state of this AccountPlanHistoryM.  # noqa: E501
        :rtype: int
        """
        return self._new_dunning_state

    @new_dunning_state.setter
    def new_dunning_state(self, new_dunning_state):
        """Sets the new_dunning_state of this AccountPlanHistoryM.

        Current dunning state of the plan instance.  # noqa: E501

        :param new_dunning_state: The new_dunning_state of this AccountPlanHistoryM.  # noqa: E501
        :type: int
        """

        self._new_dunning_state = new_dunning_state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountPlanHistoryM):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
