# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AcctSuppField(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'acct_supp_field_name': 'str',
        'acct_supp_field_value': 'str'
    }

    attribute_map = {
        'acct_supp_field_name': 'acct_supp_field_name',
        'acct_supp_field_value': 'acct_supp_field_value'
    }

    def __init__(self, acct_supp_field_name=None, acct_supp_field_value=None):  # noqa: E501
        """AcctSuppField - a model defined in Swagger"""  # noqa: E501

        self._acct_supp_field_name = None
        self._acct_supp_field_value = None
        self.discriminator = None

        if acct_supp_field_name is not None:
            self.acct_supp_field_name = acct_supp_field_name
        if acct_supp_field_value is not None:
            self.acct_supp_field_value = acct_supp_field_value

    @property
    def acct_supp_field_name(self):
        """Gets the acct_supp_field_name of this AcctSuppField.  # noqa: E501

          # noqa: E501

        :return: The acct_supp_field_name of this AcctSuppField.  # noqa: E501
        :rtype: str
        """
        return self._acct_supp_field_name

    @acct_supp_field_name.setter
    def acct_supp_field_name(self, acct_supp_field_name):
        """Sets the acct_supp_field_name of this AcctSuppField.

          # noqa: E501

        :param acct_supp_field_name: The acct_supp_field_name of this AcctSuppField.  # noqa: E501
        :type: str
        """

        self._acct_supp_field_name = acct_supp_field_name

    @property
    def acct_supp_field_value(self):
        """Gets the acct_supp_field_value of this AcctSuppField.  # noqa: E501

          # noqa: E501

        :return: The acct_supp_field_value of this AcctSuppField.  # noqa: E501
        :rtype: str
        """
        return self._acct_supp_field_value

    @acct_supp_field_value.setter
    def acct_supp_field_value(self, acct_supp_field_value):
        """Sets the acct_supp_field_value of this AcctSuppField.

          # noqa: E501

        :param acct_supp_field_value: The acct_supp_field_value of this AcctSuppField.  # noqa: E501
        :type: str
        """

        self._acct_supp_field_value = acct_supp_field_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AcctSuppField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
