# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.vendor\ariasystems\model.backup_payment_method_info import BackupPaymentMethodInfo  # noqa: F401,E501
from swagger_client.vendor\ariasystems\model.primary_payment_method_info import PrimaryPaymentMethodInfo  # noqa: F401,E501
from swagger_client.vendor\ariasystems\model.product_field import ProductField  # noqa: F401,E501


class PlanInstanceDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'acct_no': 'int',
        'user_id': 'str',
        'client_acct_id': 'str',
        'plan_instance_no': 'str',
        'client_plan_instance_id': 'str',
        'product_fields': 'list[ProductField]',
        'plan_no': 'int',
        'client_plan_id': 'str',
        'plan_name': 'str',
        'plan_units': 'int',
        'last_bill_date': 'str',
        'next_bill_date': 'str',
        'bill_thru_date': 'str',
        'status_cd': 'str',
        'status_date': 'str',
        'schedule_no': 'str',
        'master_plan_instance_balance': 'float',
        'billing_group_no': 'int',
        'client_billing_group_id': 'str',
        'dunning_group_no': 'int',
        'responsibility_level_cd': 'float',
        'responsible_plan_instance_no': 'int',
        'primary_payment_method_info': 'list[PrimaryPaymentMethodInfo]',
        'backup_payment_method_info': 'list[BackupPaymentMethodInfo]'
    }

    attribute_map = {
        'acct_no': 'acct_no',
        'user_id': 'user_id',
        'client_acct_id': 'client_acct_id',
        'plan_instance_no': 'plan_instance_no',
        'client_plan_instance_id': 'client_plan_instance_id',
        'product_fields': 'product_fields',
        'plan_no': 'plan_no',
        'client_plan_id': 'client_plan_id',
        'plan_name': 'plan_name',
        'plan_units': 'plan_units',
        'last_bill_date': 'last_bill_date',
        'next_bill_date': 'next_bill_date',
        'bill_thru_date': 'bill_thru_date',
        'status_cd': 'status_cd',
        'status_date': 'status_date',
        'schedule_no': 'schedule_no',
        'master_plan_instance_balance': 'master_plan_instance_balance',
        'billing_group_no': 'billing_group_no',
        'client_billing_group_id': 'client_billing_group_id',
        'dunning_group_no': 'dunning_group_no',
        'responsibility_level_cd': 'responsibility_level_cd',
        'responsible_plan_instance_no': 'responsible_plan_instance_no',
        'primary_payment_method_info': 'primary_payment_method_info',
        'backup_payment_method_info': 'backup_payment_method_info'
    }

    def __init__(self, acct_no=None, user_id=None, client_acct_id=None, plan_instance_no=None, client_plan_instance_id=None, product_fields=None, plan_no=None, client_plan_id=None, plan_name=None, plan_units=None, last_bill_date=None, next_bill_date=None, bill_thru_date=None, status_cd=None, status_date=None, schedule_no=None, master_plan_instance_balance=None, billing_group_no=None, client_billing_group_id=None, dunning_group_no=None, responsibility_level_cd=None, responsible_plan_instance_no=None, primary_payment_method_info=None, backup_payment_method_info=None):  # noqa: E501
        """PlanInstanceDetail - a model defined in Swagger"""  # noqa: E501

        self._acct_no = None
        self._user_id = None
        self._client_acct_id = None
        self._plan_instance_no = None
        self._client_plan_instance_id = None
        self._product_fields = None
        self._plan_no = None
        self._client_plan_id = None
        self._plan_name = None
        self._plan_units = None
        self._last_bill_date = None
        self._next_bill_date = None
        self._bill_thru_date = None
        self._status_cd = None
        self._status_date = None
        self._schedule_no = None
        self._master_plan_instance_balance = None
        self._billing_group_no = None
        self._client_billing_group_id = None
        self._dunning_group_no = None
        self._responsibility_level_cd = None
        self._responsible_plan_instance_no = None
        self._primary_payment_method_info = None
        self._backup_payment_method_info = None
        self.discriminator = None

        if acct_no is not None:
            self.acct_no = acct_no
        if user_id is not None:
            self.user_id = user_id
        if client_acct_id is not None:
            self.client_acct_id = client_acct_id
        if plan_instance_no is not None:
            self.plan_instance_no = plan_instance_no
        if client_plan_instance_id is not None:
            self.client_plan_instance_id = client_plan_instance_id
        self.product_fields = product_fields
        if plan_no is not None:
            self.plan_no = plan_no
        if client_plan_id is not None:
            self.client_plan_id = client_plan_id
        if plan_name is not None:
            self.plan_name = plan_name
        if plan_units is not None:
            self.plan_units = plan_units
        if last_bill_date is not None:
            self.last_bill_date = last_bill_date
        if next_bill_date is not None:
            self.next_bill_date = next_bill_date
        if bill_thru_date is not None:
            self.bill_thru_date = bill_thru_date
        if status_cd is not None:
            self.status_cd = status_cd
        if status_date is not None:
            self.status_date = status_date
        if schedule_no is not None:
            self.schedule_no = schedule_no
        if master_plan_instance_balance is not None:
            self.master_plan_instance_balance = master_plan_instance_balance
        if billing_group_no is not None:
            self.billing_group_no = billing_group_no
        if client_billing_group_id is not None:
            self.client_billing_group_id = client_billing_group_id
        if dunning_group_no is not None:
            self.dunning_group_no = dunning_group_no
        if responsibility_level_cd is not None:
            self.responsibility_level_cd = responsibility_level_cd
        if responsible_plan_instance_no is not None:
            self.responsible_plan_instance_no = responsible_plan_instance_no
        self.primary_payment_method_info = primary_payment_method_info
        self.backup_payment_method_info = backup_payment_method_info

    @property
    def acct_no(self):
        """Gets the acct_no of this PlanInstanceDetail.  # noqa: E501

        The Aria assigned ID of the account  # noqa: E501

        :return: The acct_no of this PlanInstanceDetail.  # noqa: E501
        :rtype: int
        """
        return self._acct_no

    @acct_no.setter
    def acct_no(self, acct_no):
        """Sets the acct_no of this PlanInstanceDetail.

        The Aria assigned ID of the account  # noqa: E501

        :param acct_no: The acct_no of this PlanInstanceDetail.  # noqa: E501
        :type: int
        """

        self._acct_no = acct_no

    @property
    def user_id(self):
        """Gets the user_id of this PlanInstanceDetail.  # noqa: E501

        The client defined user_id for the account  # noqa: E501

        :return: The user_id of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this PlanInstanceDetail.

        The client defined user_id for the account  # noqa: E501

        :param user_id: The user_id of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def client_acct_id(self):
        """Gets the client_acct_id of this PlanInstanceDetail.  # noqa: E501

        Client specified account identifier  # noqa: E501

        :return: The client_acct_id of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._client_acct_id

    @client_acct_id.setter
    def client_acct_id(self, client_acct_id):
        """Sets the client_acct_id of this PlanInstanceDetail.

        Client specified account identifier  # noqa: E501

        :param client_acct_id: The client_acct_id of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._client_acct_id = client_acct_id

    @property
    def plan_instance_no(self):
        """Gets the plan_instance_no of this PlanInstanceDetail.  # noqa: E501

        The system defined ID of the plan instance  # noqa: E501

        :return: The plan_instance_no of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._plan_instance_no

    @plan_instance_no.setter
    def plan_instance_no(self, plan_instance_no):
        """Sets the plan_instance_no of this PlanInstanceDetail.

        The system defined ID of the plan instance  # noqa: E501

        :param plan_instance_no: The plan_instance_no of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._plan_instance_no = plan_instance_no

    @property
    def client_plan_instance_id(self):
        """Gets the client_plan_instance_id of this PlanInstanceDetail.  # noqa: E501

        The client defined ID of the plan instance  # noqa: E501

        :return: The client_plan_instance_id of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._client_plan_instance_id

    @client_plan_instance_id.setter
    def client_plan_instance_id(self, client_plan_instance_id):
        """Sets the client_plan_instance_id of this PlanInstanceDetail.

        The client defined ID of the plan instance  # noqa: E501

        :param client_plan_instance_id: The client_plan_instance_id of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._client_plan_instance_id = client_plan_instance_id

    @property
    def product_fields(self):
        """Gets the product_fields of this PlanInstanceDetail.  # noqa: E501

          # noqa: E501

        :return: The product_fields of this PlanInstanceDetail.  # noqa: E501
        :rtype: list[ProductField]
        """
        return self._product_fields

    @product_fields.setter
    def product_fields(self, product_fields):
        """Sets the product_fields of this PlanInstanceDetail.

          # noqa: E501

        :param product_fields: The product_fields of this PlanInstanceDetail.  # noqa: E501
        :type: list[ProductField]
        """
        if product_fields is None:
            raise ValueError("Invalid value for `product_fields`, must not be `None`")  # noqa: E501

        self._product_fields = product_fields

    @property
    def plan_no(self):
        """Gets the plan_no of this PlanInstanceDetail.  # noqa: E501

        The Aria assigned ID of the master plan for this account  # noqa: E501

        :return: The plan_no of this PlanInstanceDetail.  # noqa: E501
        :rtype: int
        """
        return self._plan_no

    @plan_no.setter
    def plan_no(self, plan_no):
        """Sets the plan_no of this PlanInstanceDetail.

        The Aria assigned ID of the master plan for this account  # noqa: E501

        :param plan_no: The plan_no of this PlanInstanceDetail.  # noqa: E501
        :type: int
        """

        self._plan_no = plan_no

    @property
    def client_plan_id(self):
        """Gets the client_plan_id of this PlanInstanceDetail.  # noqa: E501

        The client defined ID of the plan on this instance  # noqa: E501

        :return: The client_plan_id of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._client_plan_id

    @client_plan_id.setter
    def client_plan_id(self, client_plan_id):
        """Sets the client_plan_id of this PlanInstanceDetail.

        The client defined ID of the plan on this instance  # noqa: E501

        :param client_plan_id: The client_plan_id of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._client_plan_id = client_plan_id

    @property
    def plan_name(self):
        """Gets the plan_name of this PlanInstanceDetail.  # noqa: E501

        The name of the plan on this instance  # noqa: E501

        :return: The plan_name of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._plan_name

    @plan_name.setter
    def plan_name(self, plan_name):
        """Sets the plan_name of this PlanInstanceDetail.

        The name of the plan on this instance  # noqa: E501

        :param plan_name: The plan_name of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._plan_name = plan_name

    @property
    def plan_units(self):
        """Gets the plan_units of this PlanInstanceDetail.  # noqa: E501

        The number of units assigned to this instance  # noqa: E501

        :return: The plan_units of this PlanInstanceDetail.  # noqa: E501
        :rtype: int
        """
        return self._plan_units

    @plan_units.setter
    def plan_units(self, plan_units):
        """Sets the plan_units of this PlanInstanceDetail.

        The number of units assigned to this instance  # noqa: E501

        :param plan_units: The plan_units of this PlanInstanceDetail.  # noqa: E501
        :type: int
        """

        self._plan_units = plan_units

    @property
    def last_bill_date(self):
        """Gets the last_bill_date of this PlanInstanceDetail.  # noqa: E501

        The last date on which the plan instance was billed  # noqa: E501

        :return: The last_bill_date of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._last_bill_date

    @last_bill_date.setter
    def last_bill_date(self, last_bill_date):
        """Sets the last_bill_date of this PlanInstanceDetail.

        The last date on which the plan instance was billed  # noqa: E501

        :param last_bill_date: The last_bill_date of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._last_bill_date = last_bill_date

    @property
    def next_bill_date(self):
        """Gets the next_bill_date of this PlanInstanceDetail.  # noqa: E501

        The next date on which the plan instance is scheduled to be billed  # noqa: E501

        :return: The next_bill_date of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._next_bill_date

    @next_bill_date.setter
    def next_bill_date(self, next_bill_date):
        """Sets the next_bill_date of this PlanInstanceDetail.

        The next date on which the plan instance is scheduled to be billed  # noqa: E501

        :param next_bill_date: The next_bill_date of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._next_bill_date = next_bill_date

    @property
    def bill_thru_date(self):
        """Gets the bill_thru_date of this PlanInstanceDetail.  # noqa: E501

        The date through which the plan instance has been billed  # noqa: E501

        :return: The bill_thru_date of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._bill_thru_date

    @bill_thru_date.setter
    def bill_thru_date(self, bill_thru_date):
        """Sets the bill_thru_date of this PlanInstanceDetail.

        The date through which the plan instance has been billed  # noqa: E501

        :param bill_thru_date: The bill_thru_date of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._bill_thru_date = bill_thru_date

    @property
    def status_cd(self):
        """Gets the status_cd of this PlanInstanceDetail.  # noqa: E501

        The status code of the plan instance   # noqa: E501

        :return: The status_cd of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._status_cd

    @status_cd.setter
    def status_cd(self, status_cd):
        """Sets the status_cd of this PlanInstanceDetail.

        The status code of the plan instance   # noqa: E501

        :param status_cd: The status_cd of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._status_cd = status_cd

    @property
    def status_date(self):
        """Gets the status_date of this PlanInstanceDetail.  # noqa: E501

        The date at which the plan instance entered the current status  # noqa: E501

        :return: The status_date of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._status_date

    @status_date.setter
    def status_date(self, status_date):
        """Sets the status_date of this PlanInstanceDetail.

        The date at which the plan instance entered the current status  # noqa: E501

        :param status_date: The status_date of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._status_date = status_date

    @property
    def schedule_no(self):
        """Gets the schedule_no of this PlanInstanceDetail.  # noqa: E501

        The balance of this \"stack\" (master plan instance only)  # noqa: E501

        :return: The schedule_no of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._schedule_no

    @schedule_no.setter
    def schedule_no(self, schedule_no):
        """Sets the schedule_no of this PlanInstanceDetail.

        The balance of this \"stack\" (master plan instance only)  # noqa: E501

        :param schedule_no: The schedule_no of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._schedule_no = schedule_no

    @property
    def master_plan_instance_balance(self):
        """Gets the master_plan_instance_balance of this PlanInstanceDetail.  # noqa: E501

        The balance of this \"master plan instance\"  # noqa: E501

        :return: The master_plan_instance_balance of this PlanInstanceDetail.  # noqa: E501
        :rtype: float
        """
        return self._master_plan_instance_balance

    @master_plan_instance_balance.setter
    def master_plan_instance_balance(self, master_plan_instance_balance):
        """Sets the master_plan_instance_balance of this PlanInstanceDetail.

        The balance of this \"master plan instance\"  # noqa: E501

        :param master_plan_instance_balance: The master_plan_instance_balance of this PlanInstanceDetail.  # noqa: E501
        :type: float
        """

        self._master_plan_instance_balance = master_plan_instance_balance

    @property
    def billing_group_no(self):
        """Gets the billing_group_no of this PlanInstanceDetail.  # noqa: E501

        The system defined billing group ID  # noqa: E501

        :return: The billing_group_no of this PlanInstanceDetail.  # noqa: E501
        :rtype: int
        """
        return self._billing_group_no

    @billing_group_no.setter
    def billing_group_no(self, billing_group_no):
        """Sets the billing_group_no of this PlanInstanceDetail.

        The system defined billing group ID  # noqa: E501

        :param billing_group_no: The billing_group_no of this PlanInstanceDetail.  # noqa: E501
        :type: int
        """

        self._billing_group_no = billing_group_no

    @property
    def client_billing_group_id(self):
        """Gets the client_billing_group_id of this PlanInstanceDetail.  # noqa: E501

        The client defined  defined billing group ID  # noqa: E501

        :return: The client_billing_group_id of this PlanInstanceDetail.  # noqa: E501
        :rtype: str
        """
        return self._client_billing_group_id

    @client_billing_group_id.setter
    def client_billing_group_id(self, client_billing_group_id):
        """Sets the client_billing_group_id of this PlanInstanceDetail.

        The client defined  defined billing group ID  # noqa: E501

        :param client_billing_group_id: The client_billing_group_id of this PlanInstanceDetail.  # noqa: E501
        :type: str
        """

        self._client_billing_group_id = client_billing_group_id

    @property
    def dunning_group_no(self):
        """Gets the dunning_group_no of this PlanInstanceDetail.  # noqa: E501

        The system defined dunning group ID  # noqa: E501

        :return: The dunning_group_no of this PlanInstanceDetail.  # noqa: E501
        :rtype: int
        """
        return self._dunning_group_no

    @dunning_group_no.setter
    def dunning_group_no(self, dunning_group_no):
        """Sets the dunning_group_no of this PlanInstanceDetail.

        The system defined dunning group ID  # noqa: E501

        :param dunning_group_no: The dunning_group_no of this PlanInstanceDetail.  # noqa: E501
        :type: int
        """

        self._dunning_group_no = dunning_group_no

    @property
    def responsibility_level_cd(self):
        """Gets the responsibility_level_cd of this PlanInstanceDetail.  # noqa: E501

        The responsibility level code. These are values 1 through 3 as described in the legend for this argument.  # noqa: E501

        :return: The responsibility_level_cd of this PlanInstanceDetail.  # noqa: E501
        :rtype: float
        """
        return self._responsibility_level_cd

    @responsibility_level_cd.setter
    def responsibility_level_cd(self, responsibility_level_cd):
        """Sets the responsibility_level_cd of this PlanInstanceDetail.

        The responsibility level code. These are values 1 through 3 as described in the legend for this argument.  # noqa: E501

        :param responsibility_level_cd: The responsibility_level_cd of this PlanInstanceDetail.  # noqa: E501
        :type: float
        """

        self._responsibility_level_cd = responsibility_level_cd

    @property
    def responsible_plan_instance_no(self):
        """Gets the responsible_plan_instance_no of this PlanInstanceDetail.  # noqa: E501

        Identifier for the responsible plan instance. Applicable if responsibility_level_cd is 2 or 3.  # noqa: E501

        :return: The responsible_plan_instance_no of this PlanInstanceDetail.  # noqa: E501
        :rtype: int
        """
        return self._responsible_plan_instance_no

    @responsible_plan_instance_no.setter
    def responsible_plan_instance_no(self, responsible_plan_instance_no):
        """Sets the responsible_plan_instance_no of this PlanInstanceDetail.

        Identifier for the responsible plan instance. Applicable if responsibility_level_cd is 2 or 3.  # noqa: E501

        :param responsible_plan_instance_no: The responsible_plan_instance_no of this PlanInstanceDetail.  # noqa: E501
        :type: int
        """

        self._responsible_plan_instance_no = responsible_plan_instance_no

    @property
    def primary_payment_method_info(self):
        """Gets the primary_payment_method_info of this PlanInstanceDetail.  # noqa: E501

          # noqa: E501

        :return: The primary_payment_method_info of this PlanInstanceDetail.  # noqa: E501
        :rtype: list[PrimaryPaymentMethodInfo]
        """
        return self._primary_payment_method_info

    @primary_payment_method_info.setter
    def primary_payment_method_info(self, primary_payment_method_info):
        """Sets the primary_payment_method_info of this PlanInstanceDetail.

          # noqa: E501

        :param primary_payment_method_info: The primary_payment_method_info of this PlanInstanceDetail.  # noqa: E501
        :type: list[PrimaryPaymentMethodInfo]
        """
        if primary_payment_method_info is None:
            raise ValueError("Invalid value for `primary_payment_method_info`, must not be `None`")  # noqa: E501

        self._primary_payment_method_info = primary_payment_method_info

    @property
    def backup_payment_method_info(self):
        """Gets the backup_payment_method_info of this PlanInstanceDetail.  # noqa: E501

          # noqa: E501

        :return: The backup_payment_method_info of this PlanInstanceDetail.  # noqa: E501
        :rtype: list[BackupPaymentMethodInfo]
        """
        return self._backup_payment_method_info

    @backup_payment_method_info.setter
    def backup_payment_method_info(self, backup_payment_method_info):
        """Sets the backup_payment_method_info of this PlanInstanceDetail.

          # noqa: E501

        :param backup_payment_method_info: The backup_payment_method_info of this PlanInstanceDetail.  # noqa: E501
        :type: list[BackupPaymentMethodInfo]
        """
        if backup_payment_method_info is None:
            raise ValueError("Invalid value for `backup_payment_method_info`, must not be `None`")  # noqa: E501

        self._backup_payment_method_info = backup_payment_method_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanInstanceDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
