# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ProductField(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product_field_no': 'int',
        'product_field_desc': 'str',
        'product_field_name': 'str',
        'product_field_value': 'str'
    }

    attribute_map = {
        'product_field_no': 'product_field_no',
        'product_field_desc': 'product_field_desc',
        'product_field_name': 'product_field_name',
        'product_field_value': 'product_field_value'
    }

    def __init__(self, product_field_no=None, product_field_desc=None, product_field_name=None, product_field_value=None):  # noqa: E501
        """ProductField - a model defined in Swagger"""  # noqa: E501

        self._product_field_no = None
        self._product_field_desc = None
        self._product_field_name = None
        self._product_field_value = None
        self.discriminator = None

        if product_field_no is not None:
            self.product_field_no = product_field_no
        if product_field_desc is not None:
            self.product_field_desc = product_field_desc
        if product_field_name is not None:
            self.product_field_name = product_field_name
        if product_field_value is not None:
            self.product_field_value = product_field_value

    @property
    def product_field_no(self):
        """Gets the product_field_no of this ProductField.  # noqa: E501

        The system-defined ID of the plan instance field  # noqa: E501

        :return: The product_field_no of this ProductField.  # noqa: E501
        :rtype: int
        """
        return self._product_field_no

    @product_field_no.setter
    def product_field_no(self, product_field_no):
        """Sets the product_field_no of this ProductField.

        The system-defined ID of the plan instance field  # noqa: E501

        :param product_field_no: The product_field_no of this ProductField.  # noqa: E501
        :type: int
        """

        self._product_field_no = product_field_no

    @property
    def product_field_desc(self):
        """Gets the product_field_desc of this ProductField.  # noqa: E501

        No value - only for compatibility  # noqa: E501

        :return: The product_field_desc of this ProductField.  # noqa: E501
        :rtype: str
        """
        return self._product_field_desc

    @product_field_desc.setter
    def product_field_desc(self, product_field_desc):
        """Sets the product_field_desc of this ProductField.

        No value - only for compatibility  # noqa: E501

        :param product_field_desc: The product_field_desc of this ProductField.  # noqa: E501
        :type: str
        """

        self._product_field_desc = product_field_desc

    @property
    def product_field_name(self):
        """Gets the product_field_name of this ProductField.  # noqa: E501

        The client defined ID of the plan instance field  # noqa: E501

        :return: The product_field_name of this ProductField.  # noqa: E501
        :rtype: str
        """
        return self._product_field_name

    @product_field_name.setter
    def product_field_name(self, product_field_name):
        """Sets the product_field_name of this ProductField.

        The client defined ID of the plan instance field  # noqa: E501

        :param product_field_name: The product_field_name of this ProductField.  # noqa: E501
        :type: str
        """

        self._product_field_name = product_field_name

    @property
    def product_field_value(self):
        """Gets the product_field_value of this ProductField.  # noqa: E501

        The value that was assigned to this field on this plan instance  # noqa: E501

        :return: The product_field_value of this ProductField.  # noqa: E501
        :rtype: str
        """
        return self._product_field_value

    @product_field_value.setter
    def product_field_value(self, product_field_value):
        """Sets the product_field_value of this ProductField.

        The value that was assigned to this field on this plan instance  # noqa: E501

        :param product_field_value: The product_field_value of this ProductField.  # noqa: E501
        :type: str
        """

        self._product_field_value = product_field_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
