# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SurchargeNo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'surcharge_no': 'int'
    }

    attribute_map = {
        'surcharge_no': 'surcharge_no'
    }

    def __init__(self, surcharge_no=None):  # noqa: E501
        """SurchargeNo - a model defined in Swagger"""  # noqa: E501

        self._surcharge_no = None
        self.discriminator = None

        if surcharge_no is not None:
            self.surcharge_no = surcharge_no

    @property
    def surcharge_no(self):
        """Gets the surcharge_no of this SurchargeNo.  # noqa: E501

          # noqa: E501

        :return: The surcharge_no of this SurchargeNo.  # noqa: E501
        :rtype: int
        """
        return self._surcharge_no

    @surcharge_no.setter
    def surcharge_no(self, surcharge_no):
        """Sets the surcharge_no of this SurchargeNo.

          # noqa: E501

        :param surcharge_no: The surcharge_no of this SurchargeNo.  # noqa: E501
        :type: int
        """

        self._surcharge_no = surcharge_no

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SurchargeNo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
