# coding: utf-8

"""
    Object Query API

    Object Query API for Aria billing  # noqa: E501

    OpenAPI spec version: 23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FunctionalAcctGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'functional_acct_group_no': 'int',
        'client_functional_acct_group_id': 'str'
    }

    attribute_map = {
        'functional_acct_group_no': 'functional_acct_group_no',
        'client_functional_acct_group_id': 'client_functional_acct_group_id'
    }

    def __init__(self, functional_acct_group_no=None, client_functional_acct_group_id=None):  # noqa: E501
        """FunctionalAcctGroup - a model defined in Swagger"""  # noqa: E501

        self._functional_acct_group_no = None
        self._client_functional_acct_group_id = None
        self.discriminator = None

        if functional_acct_group_no is not None:
            self.functional_acct_group_no = functional_acct_group_no
        if client_functional_acct_group_id is not None:
            self.client_functional_acct_group_id = client_functional_acct_group_id

    @property
    def functional_acct_group_no(self):
        """Gets the functional_acct_group_no of this FunctionalAcctGroup.  # noqa: E501

          # noqa: E501

        :return: The functional_acct_group_no of this FunctionalAcctGroup.  # noqa: E501
        :rtype: int
        """
        return self._functional_acct_group_no

    @functional_acct_group_no.setter
    def functional_acct_group_no(self, functional_acct_group_no):
        """Sets the functional_acct_group_no of this FunctionalAcctGroup.

          # noqa: E501

        :param functional_acct_group_no: The functional_acct_group_no of this FunctionalAcctGroup.  # noqa: E501
        :type: int
        """

        self._functional_acct_group_no = functional_acct_group_no

    @property
    def client_functional_acct_group_id(self):
        """Gets the client_functional_acct_group_id of this FunctionalAcctGroup.  # noqa: E501

          # noqa: E501

        :return: The client_functional_acct_group_id of this FunctionalAcctGroup.  # noqa: E501
        :rtype: str
        """
        return self._client_functional_acct_group_id

    @client_functional_acct_group_id.setter
    def client_functional_acct_group_id(self, client_functional_acct_group_id):
        """Sets the client_functional_acct_group_id of this FunctionalAcctGroup.

          # noqa: E501

        :param client_functional_acct_group_id: The client_functional_acct_group_id of this FunctionalAcctGroup.  # noqa: E501
        :type: str
        """

        self._client_functional_acct_group_id = client_functional_acct_group_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FunctionalAcctGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
